version: '3.5'
services:
  server:
    build: .
    ports:
      - 8080:8080
    networks:
      - docker-net
  web:
    build: 
      context: ./web
    stdin_open: true
    tty: true
    ports:
      - 8085:3000
    networks:
      - docker-net
networks:
  docker-net:
      